import type { NextPage } from "next";
import Head from "next/head";
import styles from "./home.module.scss";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.wrapper}>
                <div className={styles.container}>
                    <div className={styles.test}></div>
                </div>
            </div>
        </div>
    );
};

export default Home;
